
language: php

php:
  - '5.6'

addons:
  mariadb: '10.0'

before_script:
  - mkdir -p build/logs
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
    --configuration phpunit.xml
    --bootstrap ./vendor/autoload.php
    --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter

notifications:
  email: "bianco@javanile.org"
